# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  version: "1.1.1"

package:
  name: langchain-ibm
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/l/langchain-ibm/langchain_ibm-${{ version }}.tar.gz
  sha256: 9d240503654672ebc323e5e28fede197569e8af30db76ad8403a74d820bbbd8b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - pdm-backend
  run:
    - python >=${{ python_min }},<3.15
    - langchain-core >=1.2.22,<2.0.0
    - ibm-watsonx-ai >=1.3.37,<2.0.0
    - json-repair >=0.30.0,<1.0.0

tests:
  - python:
      imports:
        - langchain_ibm
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://github.com/langchain-ai/langchain-ibm
  repository: https://github.com/langchain-ai/langchain-ibm
  summary: An integration package connecting IBM watsonx.ai and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pb01ka
    - killua156
